author: Brandon Riffle randon@devoverflow.com
name: Needs
main: com.devoverflow.reimagined.needs.Needs
version: 1.0
description: >
             A collection of commands and Utilites.
commands:
  whereami:
    aliases: [where]
    description: Tells player what world there are in.
    usage: /<command>
    perm: Needs.whereami
  world:
    aliases: [w, wtp]
    description: Needs World interface.
    usage: /<command> [list|go]
    perm: Needs.world
  tp:
    aliases: [teleport]
    description: Teleport's player to cords or another player.
    usage: /<command>
    perm: Needs.tp
  tpto:
    description: Teleport's executor to target.
    usage: /<command>
    perm: Needs.tpto
  tphere:
    description: Teleport's target to executor.
    usage: /<command>
    perm: Needs.tphere
  sethome:
    description: Set the players respawn location.
    usage: /<command>
    perm: Needs.sethome
  back:
    description: Allow player to return to death point.
    usage: /<command>
    perm: Needs.back