author: Brandon Riffle randon@devoverflow.com
name: Needs
main: com.devoverflow.reimagined.needs.Needs
version: beta 20131220a
description: >
             A collection of commands and Utilites.
commands:
  spawn:
    description: Take player to world spawn.
    usage: /<command>
    perm: Needs.spawn
  waypoint:
    aliases: [wp]
    description: Waypoint system.
    usage: /<command> <add|del|info|list|go> [wpname]
    perm: Needs.waypoint
  home:
    description: Take player to their home.
    usage: /<command>
    perm: Needs.home
  whereami:
    aliases: [where]
    description: Tells player what world there are in.
    usage: /<command>
    perm: Needs.whereami
  world:
    aliases: [w, wtp]
    description: Needs World interface.
    usage: /<command> [list|go]
    perm: Needs.world
  tp:
    aliases: [teleport]
    description: Teleport's player to cords or another player.
    usage: /<command>
    perm: Needs.tp
  tpto:
    description: Teleport's executor to target.
    usage: /<command>
    perm: Needs.tpto
  tphere:
    description: Teleport's target to executor.
    usage: /<command>
    perm: Needs.tphere
  sethome:
    description: Set the players respawn location.
    usage: /<command>
    perm: Needs.sethome
  back:
    description: Allow player to return to death point.
    usage: /<command>
    perm: Needs.back
    
permissions:
  Needs.*:
    description: Gives full access to needs.
    children:
      Needs.spawn
      Needs.tp
      Needs.tpto
      Needs.tphere
      Needs.sethome
      Needs.home
      Needs.whereami
      Needs.back
      Needs.world
      Needs.waypoint